[package]
name = "restora-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
restora-infra.workspace = true
restora-domain.workspace = true
restora-api.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
